modLoader = "javafml"
loaderVersion = "[49,)"
#issueTrackerURL = ""
license = "LGPL-3.0-or-later"

[[mods]]
modId = "tcl_test"
version = "1"
displayName = "TCL Test"
authors = "Prototik, isXander"
description = '''
Test mod for TCL
'''
#logoFile = ""

[[dependencies.tcl_test]]
modId = "forge"
mandatory = true
versionRange = "[49,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tcl_test]]
modId = "minecraft"
mandatory = true
versionRange = "1.20.4"
ordering = "NONE"
side = "BOTH"
