modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = ""
license = "LGPL-3.0-or-later"

[[mods]]
modId = "tcl_test"
version = "1"
displayName = "TCL Test"
authors = "Prototik, isXander"
description = '''
Test mod for TCL
'''
#logoFile = ""

[[dependencies.tcl_test]]
modId = "neoforge"
type = "required"
versionRange = "[20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tcl_test]]
modId = "minecraft"
type = "required"
versionRange = "1.20.4"
ordering = "NONE"
side = "BOTH"

[[dependencies.tcl_test]]
modId = "the_config_lib"
type = "required"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"
